# source: https://github.com/briancappello/flask-unchained-react-spa/blob/master/docker-compose.yaml
---
version: '2.3'

services:

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 8888:8888
    environment:
      - API_HOST=backend
      - API_PORT=5000
      - NODE_ENV=production
    entrypoint:
      - /frontend-entrypoint.sh

  postgres:
    image: postgres:11.1-alpine
    ports:
      - 5442:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql
      - ./docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    links:
      - postgres
      - redis
    environment:
      - FLASK_DATABASE_HOST=postgres
      - FLASK_REDIS_HOST=redis
    entrypoint:
      - /flask-entrypoint.sh
    ports:
      - 5000:5000

  redis:
    image: redis:5.0-alpine
    command: redis-server
    volumes:
      - ./docker/redis/data:/data
    expose:
      - 6379

  celery_worker:
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      - FLASK_REDIS_HOST=redis
    mem_limit: 10G
    entrypoint:
      - /celery-worker-entrypoint.sh

  celery_beat:
    image: zilleanai/zillean_backend
    environment:
      - FLASK_REDIS_HOST=redis
    entrypoint:
      - /celery-beat-entrypoint.sh
