# source: https://github.com/briancappello/flask-unchained-react-spa/blob/master/docker-compose.yaml
---
version: '2.3'

services:

  frontend:
    image: gitlab.chriamue.de:4567/mlplatform/mlplatform_frontend
    ports:
      - 8888:8888  # access the app at localhost:8888
      - 5555:5555  # access webpack bundle analyzer at localhost:5555
    environment:
      - API_HOST=backend
      - API_PORT=5000
    entrypoint:
      - /frontend-entrypoint.sh

  postgres:
    image: postgres:9.6.5
    ports:
      - 5442:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql
      - ./docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  backend:
    build: .
    links:
      - postgres
      - redis
    environment:
      - FLASK_DATABASE_HOST=postgres
      - FLASK_REDIS_HOST=redis
    entrypoint:
      - /flask-entrypoint.sh
    ports:
      - 5000:5000

  redis:
    image: redis:3.2-alpine
    command: redis-server
    volumes:
      - ./docker/redis/data:/data
    expose:
      - 6379

  celery_worker:
    image: gitlab.chriamue.de:4567/mlplatform/mlplatform_backend
    environment:
      - FLASK_REDIS_HOST=redis
      - FLASK_MAIL_HOST=mailhog
      - FLASK_MAIL_PORT=1025
    entrypoint:
      - /celery-worker-entrypoint.sh

  celery_beat:
    image: gitlab.chriamue.de:4567/mlplatform/mlplatform_backend
    environment:
      - FLASK_REDIS_HOST=redis
    entrypoint:
      - /celery-beat-entrypoint.sh